apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota
  namespace: my-namespace
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 1Gi
    limits.cpu: "100"
    limits.memory: 200Gi
