apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-stress
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: stress-app
  template:
    metadata:
      labels:
        app: stress-app
    spec:
      containers:
      - name: stress-generator
        image: stress:1.0.0
        args: ["--cpu","2","--vm","1","--vm-bytes","500M","--timeout","600s"]
        resources:
          requests:
            cpu: "500m"
            memory: "1000Mi"
          limits:
            cpu: "1000m"
            memory: "1000Mi"
