apiVersion: v1
kind: Namespace
metadata:
  name: my-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  namespace: my-app
spec:
  replicas: 2 
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: this-is-my-app
  template:
    metadata:
      labels:
        app: this-is-my-app
    spec:
      containers:
        - name: my-app
          image: my-app:1.0.2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-app
spec:
  selector:
    app: this-is-my-app
  ports:
    - protocol: TCP
      port: 3000 
      targetPort: 8080

