apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 2 
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: this-is-my-app
  template:
    metadata:
      labels:
        app: this-is-my-app
    spec:
      containers:
      - name: my-app
        image: my-app:1.0.0
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
            
