apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-app:1.0.0
    volumeMounts:
    - name: property
      mountPath: /app/resources
  volumes:
  - name: property
    configMap:
      name: my-config
      items:
      - key: my-property
        path: application.properties