apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv001
spec:
  capacity:
    storage: 10Gi
  storageClassName: my-storage
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /pv-test/pv001
