apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-app:1.0.0
    lifecycle:
      preStop:
        exec:
          command: ["echo", "Hasta La Vista, Baby!"]